# Generated by Django 4.2.5 on 2024-09-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ruc', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('historial', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
