# Generated by Django 4.2.5 on 2024-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('tiempo_gracia', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_recurrencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=50)),
                ('intervalo', models.IntegerField()),
                ('dia_semana', models.IntegerField(blank=True, null=True)),
                ('dia_mes', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'citas_recurrentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'citas_servicios',
                'managed': False,
            },
        ),
    ]
