# Generated by Django 4.2.5 on 2024-10-13 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citaservicio',
            table='cita_servicios',
        ),
    ]
